name: Run LAMMPS-Python tests

on:
  push:
    branches:
    - main
    - tests

  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        torch-version: [1.10.0]
        nequip-branch: ["main"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        TORCH: "${{ matrix.torch-version }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install torch==${TORCH} -f https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install pytest
    - name: Install NequIP
      env:
          NEQUIP: "${{ matrix.nequip-branch }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install "https://github.com/mir-group/nequip/archive/${NEQUIP}.zip"
    - name: Fetch and build LAMMPS
      run: |
        BASE_DIR=`pwd`
        mkdir lammps_dir/
        cd lammps_dir/
        wget "https://github.com/lammps/lammps/archive/release.zip"
        unzip release.zip
        rm release.zip
        cd ..
        ./patch_lammps.sh lammps_dir/lammps/
        cd lammps_dir/lammps/
        mkdir build/
        cd build/
        cmake ../cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`
        make -j$(nproc)
        cd $BASE_DIR
    - name: Run tests with pytest
      run: |
        LAMMPS=lammps_dir/lammps/build/lmp pytest tests/
